### ISSUE TITLE
newbie here, error on usage

### ISSUE THREAD

**Issue by soapchan** [MichalKacprzak99/pathfinding-pygame#1]
C:\Users\noahf\pathfinding-pygame\Scripts\python.exe C:/Users/noahf/Desktop/pathfinding-pygame/pathfinding-pygame/main.py 
Traceback (most recent call last):
  File "C:/Users/noahf/Desktop/pathfinding-pygame/pathfinding-pygame/main.py", line 1, in <module>
    from app import Application
  File "C:\Users\noahf\Desktop\pathfinding-pygame\pathfinding-pygame\app.py", line 1, in <module>
    import pygame as pg
  File "C:\Users\noahf\pathfinding-pygame\lib\site-packages\pygame\__init__.py", line 81, in <module>
    from pygame.base import * # pylint: disable=wildcard-import; lgtm[py/polluting-import]
ModuleNotFoundError: No module named 'pygame.base'

Process finished with exit code 1

idk why it happens, ive tried pip installing it but error

**Comment by jamespblloyd-uwa** [comment]
I do not code on a Windows machine, which you clearly are, but my guess is that you do not have the dependencies needed to run the game. You should try using conda or mamba to install many of the python packages it needs as I find that it is better than pip. But you will probably need pip for the pathfinding package, as I could not use conda/mamba to find it.
